LOCATION_BLACKLIST = [
    "loveland",
    "longmont",
    "lonmont",
    "estes park",
    "lafayette",
    "louisville",
    "westminster",
    "broomfield",
    "gunbarrel",
    "eldora",
    "mccaslin",
    "prospect",
    "interlocken",
    "copper ridge",
    "coal creek canyon",
    "denver",
    "erie",
    "blue sky",
    "gold hill",
    "lyons",
    "summit boulevard",
    "nederland",
    "fourmile",
    "arvada",
    "superior",
    "greeley",
    "niwot",
    "northglenn",
    "black hawk",
    "firestone",
    "spine",
    "peaceful valley",
    "el paso",
    "via varra",
    "frederick",
    "logan mill",
    "mead",
    "airport",
    "thornton",
    "flatiron mall",
    "westminister",
    "wadsworth pkwy",
    "kings ridge",
    "east village flats",
    "winter park",
    "hover",
    "hunters ridge",
    "supeior",
    "n boco",
    "ken pratt",
    "berthoud",
    "campion",
    "hygiene",
    "johnstown",
    "dacono",
    "rocky mountain national park",
    "tough time leasing"
  ]
