TITLE_BLACKLIST = [
  "shared living",
  "furnished",
  "microwave, ge appliances, great location!",
  "longmont",
  "canterwood",
  "free rent",
  "tour today & save",
  "housemate wanted",
  "love to shop",
  "never too late to find the perfect new home",
  "here today, gone tomorrow",
  "good things go fast",
  "roommate needed",
  "roommates needed",
  "zero down",
  "you ought to see this captivating",
  "hurry in today",
  "we've got units today",
  "come get a brand new cozy apartment",
  "won't keep you house bound",
  "down payment assistance",
  "self-guided tour",
  "room for rent",
  "senior housing",
  "properties in boulder co",
  "erie",
  "longmont",
  "louisville",
  "lafayette",
  "in boulder 80309",
  "charming apartment homes for rent in boulder co",
  "stunning home ready right now",
  "find apartments in boulder co",
  "we have units in boulder co",
  "mountain home",
  "for rent in boulder co",
  "housing in boulder co",
  "properties today in boulder co",
  "gold run condominium",
  "gregory creek",
  "looking for roommate",
  "roommate wanted",
  "renovated apartments for rent near downtown pearl and the hill",
  "apartment for rent in private home",
  "at the seasons",
  "@ the seasons",
  "at redstone ranch",
  "gregory creek",
  "find housing today in boulder co",
  "easy purchase programs offered",
  "easy purchase progams offered",
  "broomfield",
  "estes park",
  "4 br",
  "5 br",
  "6 br",
  "7 br",
  "8 br",
  "9 br",
  "10 br",
  "11 br",
  "11br",
  "12br",
  "pre-lease",
  "pre-leasing",
  "prelease",
  "preleasing",
  "pre lease",
  "pre leasing",
  "pre - fall lease",
  "fall lease",
  "leasing for fall",
  "senior accomodations",
  "live w/ good company for $500 or less",
  "find assisted living",
  "senior communities",
  "buddha student rentals",
  "credit score",
  "use business credit",
  "own a home",
  "100% financing",
  "100s of CU student properties"
]
